<?php

// OH SNAP! BULLETIN
// Application Configuration File
// Generated By Oh Snap! Bulletin Setup Wizard

// WARNING:
// Edit this file at your own risk, as it is not recommended.
// If you need to make a configuration change, please use
// the administrators control panel.

if ( ! defined( '_SNAP_INIT' ) ) { die( '<h1>Oh Snap! Bulletin Error</h1>You do not valid permissions to access this file directly.' ); }

$CFG['db_driver'] = 'mysql';
$CFG['db_hostname'] = 'localhost';
$CFG['db_port'] = 3306;
$CFG['db_database'] = 'yourihos_snapdev';
$CFG['db_username'] = 'yourihos_tester';
$CFG['db_password'] = '1Meridian7!';
$CFG['db_persistant'] = false;
$CFG['db_log_errors'] = false;
$CFG['db_prefix'] = 'ohsnap_';
$CFG['logs_dir'] = 'logs';
$CFG['db_logs_dir'] = 'db';
$CFG['gzip_compression'] = true;
$CFG['db_cache'] = true;
$CFG['db_cache_method'] = 'filecache';
$CFG['db_cache_dir'] = 'db';
$CFG['cache_dir'] = 'cache';

?>